service: hashslowdemo1
runtime: go115
instance_class: B1
basic_scaling:
  max_instances: 5
  idle_timeout: 1m

# vpc_access_connector:
#   name: "projects/fader4/locations/europe-west1/connectors/demo2"

handlers:
  - url: /.*
    script: auto
